# Generated by Django 6.0.1 on 2026-01-21 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_commande', models.CharField(choices=[('licence', 'Licence'), ('service', 'Service IMEI')], max_length=20)),
                ('nom_produit', models.CharField(max_length=200)),
                ('prix', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('username_service', models.CharField(max_length=150)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('succes', 'Succès'), ('echec', 'Échec')], default='attente', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
