# Generated by Django 6.0.1 on 2026-01-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0002_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
