# Generated by Django 6.0.1 on 2026-01-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0003_alter_commande_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='prix',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('succes', 'Succès'), ('refuse', 'Refusée')], default='attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historique',
            name='nom_service',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historique',
            name='prix',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historique',
            name='statut',
            field=models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec')], max_length=20),
        ),
        migrations.AlterField(
            model_name='licence',
            name='prix',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='serviceimei',
            name='prix',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validée'), ('refuse', 'Refusée')], default='attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='solde',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
