# Generated by Django 6.0.1 on 2026-01-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0004_alter_commande_prix_alter_commande_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('wave', 'Wave'), ('mtn', 'MTN Money'), ('orange', 'Orange Money')], max_length=20, unique=True)),
                ('numero', models.CharField(max_length=30)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
