# Generated by Django 6.0.1 on 2026-01-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0005_paymentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='imei',
            field=models.CharField(blank=True, help_text='IMEI du téléphone (uniquement pour service IMEI)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='photo_lien',
            field=models.URLField(blank=True, help_text='Lien de la photo du téléphone (hébergée en ligne)', max_length=1000, null=True),
        ),
    ]
