# Generated by Django 6.0.1 on 2026-01-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0006_commande_imei_commande_photo_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='need_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='need_imei',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licence',
            name='need_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licence',
            name='need_username',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceimei',
            name='need_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceimei',
            name='need_imei',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceimei',
            name='need_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceimei',
            name='need_username',
            field=models.BooleanField(default=True),
        ),
    ]
