# Generated by Django 6.0.1 on 2026-01-25 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0007_licence_need_email_licence_need_imei_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Texte'), ('email', 'Email'), ('number', 'Nombre'), ('url', 'Lien'), ('textarea', 'Zone de texte')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('licence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='serveur.licence')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='serveur.serviceimei')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='serveur.commande')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveur.customfield')),
            ],
        ),
    ]
