# Generated by Django 6.0.1 on 2026-01-25 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0008_customfield_commandefieldvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customfield',
            old_name='required',
            new_name='obligatoire',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='label',
        ),
        migrations.AddField(
            model_name='customfield',
            name='type',
            field=models.CharField(choices=[('text', 'Texte'), ('number', 'Nombre'), ('email', 'Email'), ('imei', 'IMEI'), ('url', 'Lien')], default='text', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandefieldvalue',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='serveur.commande'),
        ),
    ]
