# Generated by Django 6.0.1 on 2026-01-25 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0009_rename_required_customfield_obligatoire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('demande_email', models.BooleanField(default=True)),
                ('demande_username', models.BooleanField(default=True)),
                ('demande_imei', models.BooleanField(default=False)),
                ('demande_photo', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveur.category')),
            ],
        ),
    ]
