# Generated by Django 6.0.1 on 2026-01-25 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0011_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='service_imei',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imei_custom_fields', to='serveur.serviceimei'),
        ),
    ]
