# Generated by Django 6.0.1 on 2026-01-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0012_customfield_service_imei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='service_imei',
        ),
        migrations.AddField(
            model_name='customfield',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='serveur.category'),
            preserve_default=False,
        ),
    ]
