# Generated by Django 6.0.1 on 2026-01-26 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0013_remove_customfield_service_imei_customfield_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='serveur.service'),
        ),
    ]
