# Generated by Django 6.0.1 on 2026-01-26 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0014_alter_customfield_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='serveur.category'),
        ),
    ]
