# Generated by Django 6.0.1 on 2026-01-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0016_alter_paymentconfig_methode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfig',
            name='methode',
            field=models.CharField(choices=[('wave', 'Wave'), ('mtn', 'MTN Money'), ('orange', 'Orange Money'), ('usdt_trc20', 'USDT TRC20'), ('usdt_erc20', 'USDT ERC20'), ('usdt_bep20', 'USDT BEP20')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='numero',
            field=models.CharField(max_length=100),
        ),
    ]
